# Makes the Install Package.
# This Makefile is for NMAKE.
# Copyright (C) 2007-2013 kaoru
# $Id$

DEL=del /q
CANDLE=candle
LIGHT=light -ext WixUIExtension

MSI_OUTPUT_DIR=..\bin
TARGET=$(MSI_OUTPUT_DIR)\bobura.msi


all: $(TARGET)

clean:
	$(DEL) *.wixobj
	$(DEL) $(MSI_OUTPUT_DIR)\*.wixpdb
	$(DEL) $(TARGET)

$(TARGET): main.wixobj layout.wixobj feature.wixobj
	$(LIGHT) -out $@ $**

.SUFFIXES: .wxs

.wxs.wixobj:
	$(CANDLE) -out $@ $<
